FROM python:3.11-slim

WORKDIR /app

COPY frontend/requirements_front.txt .

RUN pip install --no-cache-dir -r requirements_front.txt

COPY . .

EXPOSE 8501

CMD ["sh", "-c", "streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0"]