FROM python:3.11-slim

WORKDIR /app

COPY requirements_front.txt .

RUN pip install --no-cache-dir -r requirements_front.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]